/**:
  ros__parameters:
    # logger
    activate_debug_log: false

    # io类型(包含通讯协议和角色，指的是本机角色，而非GNSS设备角色),使用第一个
    io_type: serial # 支持三种: serial, tcp_client, udp_server
    serial:
      portname: "/dev/ttyV1"
      baudrate: 9600
      hw_flow_control: "off"
    tcp_client:
      remote_ip: "192.168.3.1" # 远端服务器地址
      remote_port: 28784 # 远端服务器端口
    udp_server:
      host_port: 8080 # 本地端口,用于接收消息
    can:
      port: "/dev/can0"

    # frame_id列表
    frame_id: gnss
    imu_frame_id: imu
    poi_frame_id: base_link
    vsm_frame_id: vsm
    aux1_frame_id: aux1
    vehicle_frame_id: base_link
    local_frame_id: odom

    # time
    use_gnss_time: false
    ntp_server: true
    latency_compensation: true

    publish:
      # For both GNSS and INS Rxs
      auto_publish: false
      publish_only_valid: false
      gpgga: false
      gprmc: false
      gpst: false
      pose: false
      twist: true
      imu: true
      localization: true
      tf: true


    # INS-Specific Parameters

    ins_spatial_config:
      imu_orientation:
        theta_x: 0.0
        theta_y: 0.0
        theta_z: 0.0
      poi_lever_arm:
        delta_x: 0.0
        delta_y: 0.0
        delta_z: 0.0
      ant_lever_arm:
        x: 0.0
        y: 0.0
        z: 0.0
      vsm_lever_arm:
        vsm_x: 0.0
        vsm_y: 0.0
        vsm_z: 0.0
